"""migration-002

Revision ID: cd73efbaf17d
Revises: 8460e06a6ddb
Create Date: 2023-05-14 14:52:27.845429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cd73efbaf17d'
down_revision = '8460e06a6ddb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_pending_query', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('has_pending_query')

    # ### end Alembic commands ###
