"""migration-003

Revision ID: dcf7c831b5c7
Revises: cd73efbaf17d
Create Date: 2023-05-15 09:52:00.987015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dcf7c831b5c7'
down_revision = 'cd73efbaf17d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('state', sa.Integer(), nullable=True))
        batch_op.drop_column('has_pending_query')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('has_pending_query', sa.BOOLEAN(), autoincrement=False, nullable=True))
        batch_op.drop_column('state')

    # ### end Alembic commands ###
